services:
  garnet:
    image: ghcr.io/microsoft/garnet
    command: ["--config-import-path", "/etc/garnet/garnet.conf"]
    ulimits:
      memlock: -1
    ports:
      - "6380:6380"
    volumes:
      - ./config/garnet.conf:/etc/garnet/garnet.conf
      - ./data:/data
    restart: unless-stopped